SELECT 
    COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE ID IN(
    SELECT ID FROM ECOLI_DATA
    WHERE SUBSTRING(REVERSE(BIN(GENOTYPE)), 1, 1) = 1 
    OR SUBSTRING(REVERSE(BIN(GENOTYPE)), 3, 1) = 1
)
AND SUBSTRING(REVERSE(BIN(GENOTYPE)), 2, 1) = 0;